Parse request/response before caching
roboflow/inference pull request #227
Opened 2024-01-11 20:34 UTC by robiscoding

# Description

To prevent the redis cache in the hosted api environment from growing too large, this change parses the information going into the cache if the `CONDENSED_CACHED` env var is set to true

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

- Tested in a local redis cache that the parse req/res get written to the cache when the env var is true, and that the full req/res are written when the var is false

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

2024-01-16 21:27 UTC, paulguerrie requested changes
Looking good so far! Just a couple small comments.

2024-01-16 21:27 UTC, paulguerrie commented on inference/core/env.py
> +CONDENSED_CACHED = str2bool(os.getenv("CONDENSED_CACHED", False))
Should we default this to True?

2024-01-16 21:27 UTC, paulguerrie commented on inference/core/cache/transforms.py
> +    request = jsonable_encoder(infer_request.dict())
I think we can exclude fields which might make this line run faster. So maybe, something like:
```suggestion
    excluded_fields = ['image'] if CONDENSED_CACHE else []
    request = jsonable_encoder(infer_request.dict(exclude=excluded_fields))
```

Docs for `.dict(...)`: https://docs.pydantic.dev/1.10/usage/exporting_models/

2024-01-24 14:30 UTC, paulguerrie approved these changes

2024-02-08 19:32 UTC, probicheaux approved these changes
lgtm

2024-02-09 17:35 UTC, SolomonLake approved these changes

2024-02-09 20:29 UTC, merged