Add model upload guidance
roboflow/inference pull request #245
Opened 2024-01-30 11:50 UTC by capjamesg

# Description

This PR adds guidance on how to upload weights to Roboflow for deployment, and more core model navigation in the `Models` subfolder.

## Type of change

- [X] Documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

You can test this change by clicking "Models" in the navigation bar and ensuring the `How to Load a Model` page appears with three links. Each link should resolve.

## Any specific deployment considerations

N/A

## Docs

N/A

2024-01-31 16:04 UTC, paulguerrie requested changes

2024-01-31 16:04 UTC, paulguerrie commented on docs/models/from_local_weights.md
> +- yolov7, yolov7-seg
I don't think we support yolov7 object detection, just yolov7-seg.

2024-01-31 16:04 UTC, paulguerrie commented on docs/models/supported_models.md
> +- YOLOv5 (Classification, Segmentation, Object Detection)
I don't think we support yolov5 classificaiton.

2024-02-20 10:40 UTC, capjamesg commented
@paulguerrie This PR has been updated per your feedback.

2024-03-07 15:17 UTC, PawelPeczek-Roboflow approved these changes

2024-03-07 15:18 UTC, merged