Peter/yolonas
roboflow/inference pull request #246
Opened 2024-01-31 02:15 UTC by probicheaux

# Description

Adds yolonas to inference

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Tested locally w/ docker

## Any specific deployment considerations

No
## Docs

-   [ ] Docs updated? What were the changes:

2024-01-31 17:28 UTC, paulguerrie requested changes
Code looks good! Can you add some test cases to the regression tests?

2024-02-01 11:46 UTC, PawelPeczek-Roboflow commented
I would also request tests in a scheme presented in `tests.inference.models_predictions_tests` where we shall test some arbitrary weights of a model, regardless of the functionality of Roboflow platfrom - this is faster and less flaky to exectue

2024-02-05 13:12 UTC, PawelPeczek-Roboflow approved these changes
LGTM

2024-02-05 15:36 UTC, paulguerrie approved these changes

2024-02-05 16:39 UTC, merged