Add YOLO-World model documentation
roboflow/inference pull request #276
Opened 2024-02-19 12:13 UTC by capjamesg

# Description

This PR adds instructions on how to use YOLO-World to the Inference documentation.

## Type of change

- [ ] Documentation improvements

## How has this change been tested, please provide a testcase or example of how you tested the change?

You can test this project by navigating to the Models tab, click "YOLO World", and ensure the page opens properly.

## Any specific deployment considerations

N/A

## Docs

N/A

2024-02-19 12:24 UTC, PawelPeczek-Roboflow requested changes
We shall also include examples of running the requests against HTTP API with inference_sdk

2024-02-19 13:06 UTC, capjamesg commented
@PawelPeczek-Roboflow Do you have code to share for those methods?

2024-02-19 13:26 UTC, PawelPeczek-Roboflow commented
```python
result = client.infer_from_yolo_world(
    inference_input=["https://media.istockphoto.com/id/1417882544/photo/large-group-of-cats-and-dogs-looking-at-the-camera-on-blue-background.jpg?s=612x612&w=0&k=20&c=kGKANSIFdNfhBJMipyuaKU4BcVE1oELWev9lF2ickE0="]*3,
    class_names=["dog", "cat"],
    model_version="m",
    confidence=0.1,
)
```
there is also async version

```python
result = await client.infer_from_yolo_world_async(
    inference_input=["https://media.istockphoto.com/id/1417882544/photo/large-group-of-cats-and-dogs-looking-at-the-camera-on-blue-background.jpg?s=612x612&w=0&k=20&c=kGKANSIFdNfhBJMipyuaKU4BcVE1oELWev9lF2ickE0="]*3,
    class_names=["dog", "cat"],
    model_version="m",
    confidence=0.1,
)
```

and if one `inefrence server start` and `pip install inference-sdk` first then this should work out of the box

2024-02-19 13:27 UTC, PawelPeczek-Roboflow commented
this is example for batch requests

2024-02-19 13:27 UTC, PawelPeczek-Roboflow commented
one may also give np array, PIL or single file path / url - as per standard way of specifying images in sdk

2024-02-20 13:38 UTC, PawelPeczek-Roboflow commented on docs/foundation/yolo_world.md
> +    detections = sv.Detections.from_inference(results)
afaik we return list of dictionaries, so probably results[0] is appropriate here

2024-02-20 13:39 UTC, PawelPeczek-Roboflow commented on docs/foundation/yolo_world.md
> +        api_url="http://127.0.0.1:9001",
we shall probably instruct users to run server with inference-cli and probably give a hint about `pip install ...`

2024-02-21 10:12 UTC, capjamesg commented
I have made the requested changes. Can you review again? (I can't merge without the last commit being reviewed and approved)

2024-02-21 10:25 UTC, PawelPeczek-Roboflow approved these changes

2024-02-21 10:28 UTC, merged