Add PaliGemma documentation, update table of contents
roboflow/inference pull request #429
Opened 2024-05-23 12:46 UTC by capjamesg

# Description

This PR:

1. Adds PaliGemma reference documentation
2. Re-orders the Table of Contents so that foundation models are more prominent
3. Updates the licensing page to link to the canonical Roboflow licensing page

## Type of change

Documentation updates

## How has this change been tested, please provide a testcase or example of how you tested the change?

You can test this PR by opening the documentation locally and browsing the new PaliGemma page and ensuring the table of contents appears correctly.

## Any specific deployment considerations

N/A

## Docs

N/A

2024-05-24 09:58 UTC, PawelPeczek-Roboflow requested changes
LGTM apart from broken link

2024-05-24 09:58 UTC, PawelPeczek-Roboflow commented on docs/foundation/paligemma.md
> +<a href="https://github.com/IDEA-Research/GroundingDINO" target="_blank">PaliGemma</a> is a large multimodal model developed by Google Research.
Probably link is malformed

2024-05-31 09:41 UTC, grzegorz-roboflow commented on docs/foundation/paligemma.md
> +<a href="https://github.com/IDEA-Research/GroundingDINO" target="_blank">PaliGemma</a> is a large multimodal model developed by Google Research.
The link forks for me

2024-06-03 07:49 UTC, PawelPeczek-Roboflow approved these changes

2024-06-03 08:11 UTC, merged