Add Inference Windows CUDA documentation
roboflow/inference pull request #502
Opened 2024-07-02 08:56 UTC by capjamesg

# Description

This PR adds documentation that shows how to install Inference on Windows with a CUDA GPU.

## Type of change

Documentation update.

## How has this change been tested, please provide a testcase or example of how you tested the change?

You can open the documentation page to make sure it is properly formatted.

## Any specific deployment considerations

N/A

## Docs

N/A

2024-07-02 10:12 UTC, PawelPeczek-Roboflow reviewed
I do not have ability to verify commands due to lack of Windows machine - was that checked e2e? If so - docs looks legit

2024-07-02 10:38 UTC, capjamesg commented
This is what the FE team sends to customers. @sberan and @chandlersupple can confirm. I have just tagged you both as reviewers.

2024-07-02 10:47 UTC, sberan commented
> This is what the FE team sends to customers. @sberan and @chandlersupple can confirm. I have just tagged you both as reviewers.

FYI I haven’t sent this to customers, it’s been internal only.

2024-07-02 10:51 UTC, sberan requested changes
@capjamesg thanks for getting these formatted! Could you add an important blurb at the very top encouraging users to use docker as it is the preferred method of installing and will skip all this headache? I worry that people will think this is the recommended approach on Windows.

2024-07-02 10:54 UTC, sberan commented on mkdocs.yml
> +          - Install Inference GPU on Windows: quickstart/inference_gpu_windows.md
```suggestion
          - Install “bare metal” Inference GPU on Windows: quickstart/inference_gpu_windows.md
```

2024-07-02 10:55 UTC, PawelPeczek-Roboflow commented
@sberan good point!

2024-08-05 13:59 UTC, grzegorz-roboflow approved these changes

2024-08-06 07:36 UTC, capjamesg commented
@sberan I have made the requested change. Please review.

2024-08-07 17:05 UTC, sberan approved these changes
LGTM!

2024-08-07 17:54 UTC, capjamesg commented
We need a review from a code owner to merge cc @PawelPeczek-Roboflow.

2024-08-08 07:56 UTC, PawelPeczek-Roboflow approved these changes

2024-08-08 07:56 UTC, merged