Persist device id on volume
roboflow/inference pull request #547
Opened 2024-07-22 21:26 UTC by robiscoding

# Description

- Persisting DEVICE_ID so that we track monitoring data by device id more reliably

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

- Set DEVICE_ID as env var; build and run container without a volume; print the device ID; re-run with different DEVICE_ID and observe that the DEVICE_ID changes
- Re-running with changes on this branch prevents the device ID from changing

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

2024-08-06 12:45 UTC, grzegorz-roboflow requested changes

2024-08-06 12:45 UTC, grzegorz-roboflow commented on inference/core/devices/utils.py
> +    cache_dir = f"{MODEL_CACHE_DIR}/_config"
`os.path.join` is used in other parts of the codebase, lets use it here too

2024-08-06 12:45 UTC, grzegorz-roboflow commented on inference/core/devices/utils.py
> +    with open(cache_dir, "w") as f:
There is a low risk of ending up with garbage in that file due to race condition. We could consider locking https://docs.python.org/3/library/fcntl.html#fcntl.flock

```python
with open(cache_dir, "w") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        try:
            # (...)
        except Exception as exc:
            # unsuccessful write attempt
        fcntl.flock(f, fcntl.LOCK_UN)
```

2024-08-06 12:45 UTC, grzegorz-roboflow commented on inference/core/devices/utils.py
> +            json.dumps(
we can use `json.dump` instead (https://docs.python.org/3/library/json.html#json.dump)

2024-08-08 21:02 UTC, robiscoding commented
Will re-open when I have bandwidth to actively work on this

2024-08-08 21:02 UTC, closed without merging