Adds in ability to cache low res logits from prompts
roboflow/inference pull request #582
Opened 2024-08-16 01:19 UTC by probicheaux

# Description

Performs breadth first search to find the most similar prompt for loading cached logits.

Performance appears to be better when using cached logits. See no cached logits:
![sam_negative_prompted_small_no_mask](https://github.com/user-attachments/assets/8dac3153-8dc7-4c6f-b164-d1eaf9c0b7c7)
vs:
![sam_negative_prompted](https://github.com/user-attachments/assets/55bdc88d-a9db-4dbc-b832-8f59e9843390)

Additionally, adds logic to pad the input points to the sam model so that 2 different prompts with differeing number of poitns can be used.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Locally, integration tests

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

2024-08-16 01:29 UTC, probicheaux commented
Not ready for review yet

2024-08-20 14:29 UTC, probicheaux commented
Ready for review @PawelPeczek-Roboflow

2024-08-21 06:58 UTC, PawelPeczek-Roboflow commented on inference/core/env.py
> +SAM2_MAX_CACHE_SIZE = int(os.getenv("SAM_MAX_EMBEDDING_CACHE_SIZE", 1000))
I propose to decouple SAM from SAM2 in terms of env variables configuring model
plus let's enlist the config variable in [this page](https://inference.roboflow.com/server_configuration/environmental_variables/)

2024-08-21 07:35 UTC, PawelPeczek-Roboflow requested changes
There is fundamental problem I detected - algorithm used in `find_prior_prompt_in_cache(...)` is computationally intractable in scenario of not finding hit in cache.

code to reproduce:
```python
import time

from inference.core.entities.requests.sam2 import (
    Sam2EmbeddingRequest,
    Sam2InferenceRequest,
    Sam2Prompt,
    Sam2PromptSet,
    Box, Point,
    Sam2SegmentationRequest,
)
from inference.models.sam2.segment_anything2 import find_prior_prompt_in_cache

initial_prompt_set = Sam2PromptSet(
    prompts=[Sam2Prompt(
        box=Box(x=10, y=10, height=10, width=10,),
        points=[Point(x=10, y=10, positive=True)] * 5
    )] * 3
)


start = time.time()
find_prior_prompt_in_cache_local(
    initial_prompt_set=initial_prompt_set,
    image_id="some",
    cache={},
)
print(f"Duration: {(time.time() - start) * 1000}ms")
```

basically you find stack growing exponentially.

2024-08-21 19:12 UTC, probicheaux commented
@PawelPeczek-Roboflow  ready for rereview

The problem we're trying to solve is this -- Suppose you have a prompt with n points. You get a mask, and you want to negative prompt based on this mask. You have to feed that mask back in when adding the n+1st point. So when we receive the request with n+1 points, we need to go load the mask from the n point prompt. 


The reason we want to cache these masks is because they take ~300kb and we don't want to incur the latency of serialization/deserialization into np arrays, as well as network latency. This matters because smart poly is trying to run in real time for image previews.

2024-08-22 08:09 UTC, PawelPeczek-Roboflow submitted a review, later dismissed
LGTM, three minor changes:
* please add global env flag disabling functionality at server level and descriptions into changed fields in request - describing that functionality may be disabled based on server config
```
    save_logits_to_cache: bool = Field(default=False)
    load_logits_from_cache: bool = Field(default=False)
```

* `self.low_res_logits_cache: LogitsCacheType = {}` typing is wrong - this id `Dict[Tuple[str, str], LogitsCacheType]`

* return type of `find_prior_prompt_in_cache(...)` is probably `Optional[np.ndarray]`

2024-08-22 15:08 UTC, PawelPeczek-Roboflow submitted a review, later dismissed

2024-08-22 15:55 UTC, grzegorz-roboflow approved these changes

2024-08-22 16:47 UTC, grzegorz-roboflow submitted a review, later dismissed

2024-08-22 16:52 UTC, capjamesg approved these changes

2024-08-22 16:55 UTC, grzegorz-roboflow approved these changes

2024-08-22 17:15 UTC, merged