Add inference_ids to model blocks
roboflow/inference pull request #615
Opened 2024-08-28 14:25 UTC by robiscoding

# Description

- Returning inference_ids in model workflow blocks

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

- Tested by pointing workflow UI to locally running container and running inferences for each model type and confirming that the inference_id appeared in the results

## Any specific deployment considerations

- N/A

## Docs

-   [ ] Docs updated? What were the changes:

2024-08-28 17:33 UTC, PawelPeczek-Roboflow requested changes
Please confirm existence of that output in integration tests that we use blocks

on separate note: I believe that this change is to compensate for https://github.com/roboflow/inference/issues/567, right?

2024-08-28 18:03 UTC, robiscoding commented
> Please confirm existence of that output in integration tests that we use blocks
Will do, I was hoping to get some test failures here to narrow down where the changes needed to be made, but it's odd that none of them failed

> on separate note: I believe that this change is to compensate for #567, right?
Correct

2024-08-28 18:13 UTC, PawelPeczek-Roboflow commented
basically this is non-breaking change so no test fails

2024-08-29 07:17 UTC, PawelPeczek-Roboflow approved these changes

2024-08-29 07:17 UTC, merged