Add block for running pt models from local filesystem
roboflow/inference pull request #756
Opened 2024-10-24 20:42 UTC by grzegorz-roboflow

# Description

Block enables user to load *.pt model directly from local filesystem

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

e2e tested

## Any specific deployment considerations

*.pt file must be available in local filesystem

## Docs

N/A

2024-10-29 15:16 UTC, PawelPeczek-Roboflow requested changes

2024-10-29 15:16 UTC, PawelPeczek-Roboflow commented on setup.py
> +        "ultralytics": read_requirements("requirements/requirements.ultralytics.txt"),
not sure if you committed this requirements file

2024-10-29 15:16 UTC, PawelPeczek-Roboflow commented on inference/core/workflows/core_steps/models/foundation/ultralytics/v1.py
> +        if "YOLO" not in globals():
we must prevent running on hosted platform

2024-10-29 15:16 UTC, PawelPeczek-Roboflow commented on inference/core/workflows/core_steps/models/foundation/ultralytics/v1.py
> +This block expects pth file to be available within local filesystem.
Let's add more verbose docs

2025-04-03 10:32 UTC, grzegorz-roboflow commented
Closing for now

2025-04-03 10:32 UTC, closed without merging