Model monitoring export block
roboflow/inference pull request #818
Opened 2024-11-15 19:28 UTC by robiscoding

# Description

- Currently Model Monitoring does not support for inferences made by InferencePipeline. To add support, this Model Monitoring Exporter block allows users to arbitrarily send inference results to MM at a defined frequency (in seconds)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

- Tested using local workflow run when frequency is and is not in range for reporting

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

2024-11-15 19:30 UTC, robiscoding commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_exporter/v1.py
> +    frequency: Union[
I considered using the RateLimiter block, but this export block would always require that as a dependency. I'm not sure if there's a pattern for making another block required to run, so I just added this to the params for now, open to doing it another way

2024-11-15 19:32 UTC, robiscoding commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_exporter/v1.py
> +    elif isinstance(detections, dict):
What case would predictions be returned as a dict? I saw in other Blocks that predictions will either be of type sv.Detections or dict

2024-11-18 11:03 UTC, PawelPeczek-Roboflow requested changes
I have general concern with this PR - what is the quality of data acquired in that way? Is that meaningful monitoring at the end of the day? What do we want to display as the result of running monitoring about a week-long stream? How would people understand that something is wrong with the model?

I mean, we have stream running and we sub sample of predictions based on time, suggesting to update once per few seconds. We do it as this is basically unfeasible to push through the wire all predictions - but maybe - in this scenario it makes sense to compute aggregates of predictions on the client end and submit compacted results once per interval?

2024-11-18 15:14 UTC, robiscoding commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_exporter/v1.py
> +    frequency: Union[
Yeah maybe something like SamplePredictions, ReportPredictionsSample, ModelMonitoringPredictionsSampler

2024-11-21 12:55 UTC, PawelPeczek-Roboflow commented
Today we need to close the topic, otherwise `release 0.28.0` label will be removed

2024-11-21 13:54 UTC, PawelPeczek-Roboflow commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_inference_aggregator/v1.py
> +        self._last_report_time_cache_key = "roboflow_model_monitoring_last_report_time"
that would have a side effect for **all blocks of this type to have shared state of last report time** - is that desired end?

2024-11-21 13:55 UTC, PawelPeczek-Roboflow commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_inference_aggregator/v1.py
> +        time_elapsed = int((now - last_report_time).total_seconds())
type conversion to int seems not to be needed

2024-11-21 13:56 UTC, PawelPeczek-Roboflow commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_inference_aggregator/v1.py
> +def format_sv_detections_for_model_monitoring(
please change the name to reflect that `sv.Detections` and cls results are handled

2024-11-21 13:59 UTC, PawelPeczek-Roboflow commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_inference_aggregator/v1.py
> +    class_name: str
wrong typing w.r.t. actual usage

2024-11-21 14:04 UTC, PawelPeczek-Roboflow commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_inference_aggregator/v1.py
> +It aggregates predictions in memory between reports and then sends a representative sample of predictions at a regular interval specified by the `frequency` parameter.
I would elaborate on what we understand by representative - seems like "most confident for given class"

2024-11-21 14:07 UTC, PawelPeczek-Roboflow commented on inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_inference_aggregator/v1.py
> +        self._last_report_time_cache_key = "roboflow_model_monitoring_last_report_time"
* if the expectation is that it works at hosted, I would use redis with the following structure of keys `workflows:steps_cache:roboflow_core/model_monitoring_inference_aggregator@v1:{uuid4()}:last_report_time`

2024-11-22 11:18 UTC, PawelPeczek-Roboflow approved these changes
Approving under following conditions (also reported in docs):

#### 🚨 Limitations

* The block is should not be relied on when running Workflow in `inference` server or via HTTP request to Roboflow 
hosted platform, as the internal state is not persisted in a memory that would be accessible for all requests to
the server, causing aggregation to **only have a scope of single request**. We will solve that problem in future 
releases if proven to be serious limitation for clients.

* This block do not have ability to separate aggregations for multiple videos processed by `InferencePipeline` - 
effectively aggregating data for **all video feeds connected to single process running `InferencePipeline`**. 


@robiscoding in the interest of having the feature I will push the PR, also fixing tests that were broken, but I will hold you responsible for any follow-up changes if there are bug / problem reports.

2024-11-22 11:22 UTC, grzegorz-roboflow approved these changes

2024-11-22 11:30 UTC, merged

2024-11-22 13:55 UTC, robiscoding commented
> Approving under following conditions (also reported in docs):
> 
> #### 🚨 Limitations
> * The block is should not be relied on when running Workflow in `inference` server or via HTTP request to Roboflow
>   hosted platform, as the internal state is not persisted in a memory that would be accessible for all requests to
>   the server, causing aggregation to **only have a scope of single request**. We will solve that problem in future
>   releases if proven to be serious limitation for clients.
> * This block do not have ability to separate aggregations for multiple videos processed by `InferencePipeline` -
>   effectively aggregating data for **all video feeds connected to single process running `InferencePipeline`**.
> 
> @robiscoding in the interest of having the feature I will push the PR, also fixing tests that were broken, but I will hold you responsible for any follow-up changes if there are bug / problem reports.

We can work with those current limitations as the block will still provide us with some observability of inferencepipeline running in edge environments. And yes we'll be iterating on this functionality so let me know if any issues come up in the interim, thanks for the thorough review!